### ISSUE TITLE
Exception when running in debug mode

### ISSUE THREAD

**Issue by shahriar-b** [r1me/TTesseractOCR4#8]
I get the attached exception when i try to run the application using this library on debug mode 
![image](https://user-images.githubusercontent.com/15137093/42268171-6c4e8332-7fad-11e8-83d5-05c6139eb509.png)

This happens also to the attached demo, but working fine on release build config.

**Comment by laggyluk** [comment]
Having similar problem, examples work in release mode but it would be convenient to also have debug version of tesseract binaries in the repo. At least that's my guess why it doesn't work in debug build.

**Comment by danieleteti** [comment]
Any news about this?

**Comment by r1me** [comment]
Fixed with https://github.com/r1me/TTesseractOCR4/commit/6846137265414cb7f34209262aece2034e419889
However I recommend switching from CPPAN builds to Tesseract 4.1, that is set by undefining `USE_CPPAN_BINARIES` in tesseractocr.consts. Build obtainable from https://digi.bib.uni-mannheim.de/tesseract/
